# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UISerial.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 886)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.PrintgroupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrintgroupBox_2.sizePolicy().hasHeightForWidth())
        self.PrintgroupBox_2.setSizePolicy(sizePolicy)
        self.PrintgroupBox_2.setMinimumSize(QtCore.QSize(410, 810))
        self.PrintgroupBox_2.setMaximumSize(QtCore.QSize(820, 1620))
        self.PrintgroupBox_2.setObjectName("PrintgroupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.PrintgroupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.PrintgroupBox_2)
        self.lcdNumber.setMinimumSize(QtCore.QSize(280, 60))
        self.lcdNumber.setMaximumSize(QtCore.QSize(560, 120))
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_2.addWidget(self.lcdNumber)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.SerialSetButton = QtWidgets.QPushButton(self.PrintgroupBox_2)
        self.SerialSetButton.setMinimumSize(QtCore.QSize(70, 50))
        self.SerialSetButton.setMaximumSize(QtCore.QSize(140, 100))
        self.SerialSetButton.setObjectName("SerialSetButton")
        self.horizontalLayout_2.addWidget(self.SerialSetButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 5)
        self.RXtextEdit = QtWidgets.QTextEdit(self.PrintgroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.RXtextEdit.sizePolicy().hasHeightForWidth())
        self.RXtextEdit.setSizePolicy(sizePolicy)
        self.RXtextEdit.setMinimumSize(QtCore.QSize(401, 631))
        self.RXtextEdit.setMaximumSize(QtCore.QSize(742, 1140))
        self.RXtextEdit.setMouseTracking(True)
        self.RXtextEdit.setTabletTracking(True)
        self.RXtextEdit.setObjectName("RXtextEdit")
        self.gridLayout_3.addWidget(self.RXtextEdit, 1, 0, 1, 5)
        self.RxDispCheckBox = QtWidgets.QCheckBox(self.PrintgroupBox_2)
        self.RxDispCheckBox.setMinimumSize(QtCore.QSize(60, 15))
        self.RxDispCheckBox.setMaximumSize(QtCore.QSize(120, 30))
        self.RxDispCheckBox.setObjectName("RxDispCheckBox")
        self.gridLayout_3.addWidget(self.RxDispCheckBox, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(62, 37, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 1, 1, 1)
        self.BtnSave = QtWidgets.QPushButton(self.PrintgroupBox_2)
        self.BtnSave.setMinimumSize(QtCore.QSize(90, 40))
        self.BtnSave.setMaximumSize(QtCore.QSize(167, 167))
        self.BtnSave.setObjectName("BtnSave")
        self.gridLayout_3.addWidget(self.BtnSave, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(63, 37, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 3, 1, 1)
        self.btnClearReceive = QtWidgets.QPushButton(self.PrintgroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClearReceive.sizePolicy().hasHeightForWidth())
        self.btnClearReceive.setSizePolicy(sizePolicy)
        self.btnClearReceive.setMinimumSize(QtCore.QSize(90, 40))
        self.btnClearReceive.setMaximumSize(QtCore.QSize(167, 167))
        self.btnClearReceive.setObjectName("btnClearReceive")
        self.gridLayout_3.addWidget(self.btnClearReceive, 2, 4, 1, 1)
        self.gridLayout.addWidget(self.PrintgroupBox_2, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(55, 28))
        self.label_17.setMaximumSize(QtCore.QSize(55, 28))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        self.receivedLength = QtWidgets.QLabel(self.centralwidget)
        self.receivedLength.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receivedLength.sizePolicy().hasHeightForWidth())
        self.receivedLength.setSizePolicy(sizePolicy)
        self.receivedLength.setMinimumSize(QtCore.QSize(55, 28))
        self.receivedLength.setMaximumSize(QtCore.QSize(55, 28))
        self.receivedLength.setText("")
        self.receivedLength.setAlignment(QtCore.Qt.AlignCenter)
        self.receivedLength.setObjectName("receivedLength")
        self.horizontalLayout.addWidget(self.receivedLength)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setMinimumSize(QtCore.QSize(55, 28))
        self.label_19.setMaximumSize(QtCore.QSize(55, 28))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        spacerItem3 = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(550, 790))
        self.groupBox.setMaximumSize(QtCore.QSize(1110, 1580))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(530, 500))
        self.tabWidget.setMaximumSize(QtCore.QSize(1060, 1000))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout = QtWidgets.QFormLayout(self.tab)
        self.formLayout.setObjectName("formLayout")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.SetMsggroupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetMsggroupBox_3.sizePolicy().hasHeightForWidth())
        self.SetMsggroupBox_3.setSizePolicy(sizePolicy)
        self.SetMsggroupBox_3.setMinimumSize(QtCore.QSize(530, 240))
        self.SetMsggroupBox_3.setObjectName("SetMsggroupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.SetMsggroupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SetMessageBox = QtWidgets.QTextEdit(self.SetMsggroupBox_3)
        self.SetMessageBox.setObjectName("SetMessageBox")
        self.verticalLayout_2.addWidget(self.SetMessageBox)
        self.editSendData = QtWidgets.QLineEdit(self.SetMsggroupBox_3)
        self.editSendData.setMinimumSize(QtCore.QSize(370, 30))
        self.editSendData.setMaximumSize(QtCore.QSize(740, 60))
        self.editSendData.setObjectName("editSendData")
        self.verticalLayout_2.addWidget(self.editSendData)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.checkStringSend = QtWidgets.QCheckBox(self.SetMsggroupBox_3)
        self.checkStringSend.setObjectName("checkStringSend")
        self.horizontalLayout_4.addWidget(self.checkStringSend)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.BtnSend = QtWidgets.QPushButton(self.SetMsggroupBox_3)
        self.BtnSend.setMinimumSize(QtCore.QSize(40, 30))
        self.BtnSend.setMaximumSize(QtCore.QSize(167, 167))
        self.BtnSend.setObjectName("BtnSend")
        self.horizontalLayout_4.addWidget(self.BtnSend)
        spacerItem6 = QtWidgets.QSpacerItem(141, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addWidget(self.SetMsggroupBox_3, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PrintgroupBox_2.setTitle(_translate("MainWindow", "信息输出"))
        self.SerialSetButton.setText(_translate("MainWindow", "串口设置"))
        self.RxDispCheckBox.setText(_translate("MainWindow", "HEX格式"))
        self.BtnSave.setText(_translate("MainWindow", "保存"))
        self.btnClearReceive.setText(_translate("MainWindow", "清空"))
        self.label_17.setText(_translate("MainWindow", "已接收:"))
        self.label_19.setText(_translate("MainWindow", "字节"))
        self.groupBox.setTitle(_translate("MainWindow", "设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "tab_3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "tab_4"))
        self.SetMsggroupBox_3.setTitle(_translate("MainWindow", "设置信息"))
        self.checkStringSend.setText(_translate("MainWindow", "HEX格式"))
        self.BtnSend.setText(_translate("MainWindow", "发送"))

